task-4
Megoos/shri-2 pull request #1
Opened 2018-10-12 22:50 UTC by Megoos

2018-10-20 04:43 UTC, Epsilonnnn requested changes

2018-10-20 04:43 UTC, Epsilonnnn commented on server/utils/dateDiff.js
> +    var hours, minutes, seconds;
почему используется `var`, а не `let`?

2018-10-20 04:43 UTC, Epsilonnnn commented on server/index.js
> +app.get('*', (request, response) => {
получается, что если будет `post` запрос или запрос каким-нибудь другим http-методом на не существующую ручку, то  404 не выдастся?

2018-10-20 04:43 UTC, Epsilonnnn commented on server/index.js
> +                const queryTypes = request.query.type.split(':');
что будет, если `type` не строка или если `type` пустая строка?

2018-10-20 04:43 UTC, Epsilonnnn commented on server/index.js
> +var startTime = null;
https://nodejs.org/api/process.html#process_process_uptime

2018-10-20 04:43 UTC, Epsilonnnn commented on server/index.js
> +    fs.readFile(path.join(__dirname, _path), 'utf-8', (err, data) => {
было бы хорошо обернуть `fs.readFile` в промис - https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

2018-10-20 14:58 UTC, Megoos commented on server/utils/dateDiff.js
> +    var hours, minutes, seconds;
ага лучше через `let`

2018-10-20 14:58 UTC, Megoos commented on server/index.js
> +app.get('*', (request, response) => {
Сделал через мидлвару

2018-10-20 14:59 UTC, Megoos commented on server/index.js
> +var startTime = null;
Спасибо, не знал про такое. Сделал через uptime. Пришлось немного функцию преобразования времени так же поменять

2018-10-20 15:00 UTC, Megoos commented on server/index.js
> +    fs.readFile(path.join(__dirname, _path), 'utf-8', (err, data) => {
Сделал через promisify, так и в правду удобнее,

2018-10-20 15:19 UTC, Megoos commented on server/index.js
> +                const queryTypes = request.query.type.split(':');
Условием задания было если поля `type` нет возвращать весь json. Если оно есть но пустое `400`. А параметры `query` могут быть не строкой?

2018-10-20 15:20 UTC, Megoos commented
@Epsilonnnn Сделал правки по комментариям, спасибо! Все по делу)

2018-10-23 11:15 UTC, Epsilonnnn commented on server/index.js
> +                const queryTypes = request.query.type.split(':');
При запросе `/api/events?type=1&type=2&type=3` в `req.query.type` будет массив

2018-10-28 12:22 UTC, merged